
#ifndef __PORT_CFG_H__
#define __PORT_CFG_H__


#define PORTA_PIN0_DIR     OUTPUT
#define PORTA_PIN1_DIR     INPUT
#define PORTA_PIN2_DIR     INPUT
#define PORTA_PIN3_DIR     INPUT
#define PORTA_PIN4_DIR     INPUT
#define PORTA_PIN5_DIR     INPUT
#define PORTA_PIN6_DIR     INPUT
#define PORTA_PIN7_DIR     INPUT

#define PORTB_PIN0_DIR     INPUT
#define PORTB_PIN1_DIR     INPUT
#define PORTB_PIN2_DIR     INPUT
#define PORTB_PIN3_DIR     INPUT
#define PORTB_PIN4_DIR     INPUT
#define PORTB_PIN5_DIR     INPUT
#define PORTB_PIN6_DIR     INPUT
#define PORTB_PIN7_DIR     INPUT

#define PORTC_PIN0_DIR     INPUT
#define PORTC_PIN1_DIR     INPUT
#define PORTC_PIN2_DIR     INPUT
#define PORTC_PIN3_DIR     INPUT
#define PORTC_PIN4_DIR     INPUT
#define PORTC_PIN5_DIR     INPUT
#define PORTC_PIN6_DIR     INPUT
#define PORTC_PIN7_DIR     INPUT

#define PORTD_PIN0_DIR     INPUT
#define PORTD_PIN1_DIR     INPUT
#define PORTD_PIN2_DIR     INPUT
#define PORTD_PIN3_DIR     INPUT
#define PORTD_PIN4_DIR     INPUT
#define PORTD_PIN5_DIR     INPUT
#define PORTD_PIN6_DIR     INPUT
#define PORTD_PIN7_DIR     INPUT

#define PORTA_PIN0_INIT_VAL     HIGH
#define PORTA_PIN1_INIT_VAL     LOW
#define PORTA_PIN2_INIT_VAL     LOW
#define PORTA_PIN3_INIT_VAL     LOW
#define PORTA_PIN4_INIT_VAL     LOW
#define PORTA_PIN5_INIT_VAL     LOW
#define PORTA_PIN6_INIT_VAL     LOW
#define PORTA_PIN7_INIT_VAL     LOW

#define PORTB_PIN0_INIT_VAL     LOW
#define PORTB_PIN1_INIT_VAL     LOW
#define PORTB_PIN2_INIT_VAL     LOW
#define PORTB_PIN3_INIT_VAL     LOW
#define PORTB_PIN4_INIT_VAL     LOW
#define PORTB_PIN5_INIT_VAL     LOW
#define PORTB_PIN6_INIT_VAL     LOW
#define PORTB_PIN7_INIT_VAL     LOW

#define PORTC_PIN0_INIT_VAL     LOW
#define PORTC_PIN1_INIT_VAL     LOW
#define PORTC_PIN2_INIT_VAL     LOW
#define PORTC_PIN3_INIT_VAL     LOW
#define PORTC_PIN4_INIT_VAL     LOW
#define PORTC_PIN5_INIT_VAL     LOW
#define PORTC_PIN6_INIT_VAL     LOW
#define PORTC_PIN7_INIT_VAL     LOW

#define PORTD_PIN0_INIT_VAL     LOW
#define PORTD_PIN1_INIT_VAL     LOW
#define PORTD_PIN2_INIT_VAL     LOW
#define PORTD_PIN3_INIT_VAL     LOW
#define PORTD_PIN4_INIT_VAL     LOW
#define PORTD_PIN5_INIT_VAL     LOW
#define PORTD_PIN6_INIT_VAL     LOW
#define PORTD_PIN7_INIT_VAL     LOW

 
#endif  /* __PORT_CFG_H__ */

